name: Daily Sign In

on:
  workflow_dispatch:
  schedule:
    # 每天UTC时间8点运行（北京时间16点）
    - cron: '5 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run build script
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/master'))
      run: npm run build

    - name: Install dependencies
      run: npm install

    - name: Run the script with secrets
      run: node index.js
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SENDKEY: ${{ secrets.SENDKEY }}
